### ISSUE TITLE
Админка

### ISSUE THREAD

**Issue by eliseealex** [neSpecc/codex#17]

**Comment by ivanszhuravlev** [comment]
#### Описание задачи
* Эта задача важна, потому что удобно иметь компактный список статей и пользователей с возможностью правки чего-либо в них и удаления на одной странице.
* Мы это делаем, в первую очередь, для самих себя. Однако, кто будет обладать правами доступа к админке, пока неизвестно.
* "Как мы поймём, что задача выполнена хорошо?" - когда этим будет удобно пользоваться... 
* Нужно сделать две страницы со списками статей и пользователей и краткой информацией о каждой статье/пользователе, в виде таблиц. Но это неточно, потому что к админке можно много чего прикрутить.
