### ISSUE TITLE
Авторизация через FB и VK

### ISSUE THREAD

**Issue by eliseealex** [neSpecc/codex#19]

**Comment by n0str** [comment]
Отревьюить backend, фронт оформить.

**Comment by eliseealex** [comment]
Backend уже в мастере?

**Comment by eliseealex** [comment]
Или как его отревьюить?

**Comment by n0str** [comment]
А что подразумевается под авторизацией? Авторизация через VK и FB уже в мастере. Нужно ее ревьюить и смотреть что и как доделать\переделать. Но пока ждем полноценных профилей.

**Comment by eliseealex** [comment]
Короче, я переименовал в Авторизацию через FB и VK, как я понимаю, можно закрывать, да?

**Comment by n0str** [comment]
Думаю, что нужно убрать из 1.0, а issue оставить как enchancement

**Comment by eliseealex** [comment]
Ну создадим новую таску, как нужно будет =)
