### ISSUE TITLE
Привязка соц. сети

### ISSUE THREAD

**Issue by n0str** [neSpecc/codex#31]
Пишу на русском т.к. сложная структура задачи.
Необходимо продумать механизм прикрепления новых соц. сетей (в том числе объединения существующих профилей).

Я это вижу как кнопка добавления соц. сети в профиле, проверка (авторизация) и мёрдж существующих профилей каким-то образом (для начала можно удалять прикрепленный профиль со специальным статусом).

**Comment by eliseealex** [comment]
Зачем удалять прикрепленный профиль со специальным статусом?
PS — epic — это обычно задачи в которых содержаться другие задачи.

**Comment by n0str** [comment]
Я с таким сталкивался на паре сайтов. Заходишь через ВК, потом через фейсбук, получаешь два аккаунта, несколько сообщений на каждом написал. Потом решаешь их объединить, чтобы в поиске и в авторах сообщений был доступен только один общий аккаунт.
А я думал, что Epic - это эпические задания.

**Comment by eliseealex** [comment]
А, прикольно, но думаю, пока можно это не делать. Предусмотреть - конечно можно, но лучше начать с того, чтобы просто можно было привязать несколько значений.
